# Generated by Django 4.2.1 on 2023-06-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('dproduct_id', models.AutoField(default=1000, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
