# Generated by Django 4.2.1 on 2023-06-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='dproduct_id',
            new_name='product_id',
        ),
    ]
