# Generated by Django 4.2.1 on 2023-06-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_products_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='members/static/'),
        ),
    ]
